apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-prod-claim
  namespace: prod
  labels:
    tier: prod
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-prod-claim
  namespace: prod
  labels:
    tier: prod
    app: php
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: prod
  labels:
    tier: prod
    app: db
spec:
  selector:
    matchLabels:
      tier: prod
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: prod
        app: db
    spec:
      containers:
      - name: mysql-prod
        image: ecemozer/goals-project-db:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: MYSQL_DATABASE      
        resources:
          limits:
            memory: "1Gi"
            cpu: "250m"
        ports:
          - containerPort: 3306
            name: mysql-prod-port
        volumeMounts:
          - name: mysql-prod-pv
            mountPath: /var/lib/mysql
      nodeSelector:
        tier: prod
      volumes:
        - name: mysql-prod-pv
          persistentVolumeClaim:
            claimName: mysql-prod-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: prod
  labels:
    tier: prod
    app: php
spec:
  selector:
    matchLabels:
      tier: prod
      app: php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: prod
        app: php
    spec:
      containers:
      - image: ecemozer/goals-project-web:latest
        name: php-prod
        env:
        - name: PHP_DB_HOST
          value: mysql-prod-svc
        - name: PHP_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: MYSQL_USERld
        - name: PHP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: MYSQL_PASSWORD
        - name: PHP_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: MYSQL_DATABASE
        resources:
          limits:
            memory: "1Gi"
            cpu: "250m"
        ports:
        - containerPort: 80
          name: php-prod-port
        volumeMounts:
        - name: php-prod-pv
          mountPath: /var/www/html
      nodeSelector:
        tier: prod
      volumes:
      - name: php-prod-pv
        persistentVolumeClaim:
          claimName: php-prod-claim
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mysql
            topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-prod-svc
  namespace: prod
  labels:
    tier: prod
spec:
  selector:
    tier: prod
    app: db
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: php-prod-svc
  namespace: prod
  labels:
    tier: prod
    app: php
spec:
  selector:
    tier: prod
    app: php
  ports:
  - port: 80
    targetPort: 80